import { hexToChannels } from "./contrast";
import { DERIVED_CHANNEL_TOKENS, THEME_TOKENS, type ThemeColors } from "./tokens";

export const THEME_STORAGE_KEY = "dineboard.theme.v1";

export interface ThemeDefinition {
  id: string;
  name: string;
  /** URL segment for `/dashboard/themes/[themeSlug]`. */
  slug: string;
  description: string;
  /** Built-in themes can be edited but not deleted. */
  builtIn: boolean;
  colors: ThemeColors;
}

/** Shape written to `localStorage`, and read back by the pre-hydration script. */
export interface StoredThemeState {
  activeThemeId: string;
  themes: ThemeDefinition[];
}

/**
 * Writes a palette onto an element's inline style as CSS custom properties.
 *
 * Inline styles on `:root` beat the stylesheet's `:root` block, so this
 * overrides the shipped defaults without touching the stylesheet — which is
 * what lets the dashboard re-skin a statically exported site.
 */
export function applyThemeColors(colors: ThemeColors, target?: HTMLElement): void {
  const root = target ?? document.documentElement;

  for (const token of THEME_TOKENS) {
    const value = colors[token.name];
    if (value) root.style.setProperty(`--${token.name}`, value);
  }

  // Channel companions are generated, never stored, so the hex and the rgb
  // form can never describe two different colours.
  for (const token of DERIVED_CHANNEL_TOKENS) {
    const channels = hexToChannels(colors[token]);
    if (channels) root.style.setProperty(`--${token}-rgb`, channels);
  }
}

/** Removes every property this module sets, restoring the stylesheet defaults. */
export function clearThemeColors(target?: HTMLElement): void {
  const root = target ?? document.documentElement;
  for (const token of THEME_TOKENS) root.style.removeProperty(`--${token.name}`);
  for (const token of DERIVED_CHANNEL_TOKENS) root.style.removeProperty(`--${token}-rgb`);
}

/**
 * Emits the theme as a `:root` block.
 *
 * The dashboard persists to `localStorage`, which is per-browser. To make a
 * theme the shipped default for every visitor, paste this into
 * `src/app/globals.css` and redeploy — this function is the bridge between
 * "previewing a theme" and "publishing one".
 */
export function themeToCss(theme: ThemeDefinition): string {
  const lines = THEME_TOKENS.map((token) => `  --${token.name}: ${theme.colors[token.name]};`);

  const derived = DERIVED_CHANNEL_TOKENS.map((token) => {
    const channels = hexToChannels(theme.colors[token]) ?? "0 0 0";
    return `  --${token}-rgb: ${channels};`;
  });

  return [
    `/* ${theme.name} — generated by the DineBoard theme dashboard. */`,
    ":root {",
    ...lines,
    "",
    "  /* Derived channels — regenerate rather than edit by hand. */",
    ...derived,
    "}",
    "",
  ].join("\n");
}

/**
 * Source of the blocking script injected into `<head>`.
 *
 * It runs while the browser parses the HTML — before the first paint and long
 * before React hydrates — so a saved theme never flashes the shipped palette
 * first. Kept dependency-free and wrapped in try/catch because `localStorage`
 * throws outright in some privacy modes.
 */
export function themeBootstrapScript(): string {
  const tokenNames = JSON.stringify(THEME_TOKENS.map((token) => token.name));
  const derivedNames = JSON.stringify([...DERIVED_CHANNEL_TOKENS]);

  return `(function(){try{
var raw=localStorage.getItem(${JSON.stringify(THEME_STORAGE_KEY)});
if(!raw)return;
var s=JSON.parse(raw);
if(!s||!s.themes)return;
var t=null;
for(var i=0;i<s.themes.length;i++){if(s.themes[i].id===s.activeThemeId){t=s.themes[i];break}}
if(!t||!t.colors)return;
var r=document.documentElement,n=${tokenNames},d=${derivedNames},k,v,h,x;
for(var j=0;j<n.length;j++){k=n[j];v=t.colors[k];if(v)r.style.setProperty("--"+k,v)}
for(var m=0;m<d.length;m++){
k=d[m];v=t.colors[k];if(!v)continue;
h=v.replace("#","");
if(h.length===3)h=h[0]+h[0]+h[1]+h[1]+h[2]+h[2];
if(!/^[0-9a-fA-F]{6}$/.test(h))continue;
x=parseInt(h,16);
r.style.setProperty("--"+k+"-rgb",((x>>16)&255)+" "+((x>>8)&255)+" "+(x&255));
}
}catch(e){}})()`.replace(/\n/g, "");
}
